import { expect, test } from 'vitest'
import { numpadRuntimeFixture, numpadTree } from './support/numpad-runtime-fixture.js'

test('Backspace traverses parents without leaving Numpy or waiting for paints', async () => {
  const fixture = numpadRuntimeFixture()
  fixture.runtime.start()
  await fixture.settle()
  for (const digit of '011') fixture.key(digit)
  const back = () => fixture.runtime.keyDown({ code: 'Backspace', key: 'Backspace' }, true)
  expect(back()).toBe(true)
  expect(fixture.runtime.controller.getSnapshot().session.pathIds).toEqual(['controls'])
  back()
  back()
  expect(fixture.runtime.controller.getSnapshot().session).toEqual({ active: true, pathIds: [], pendingDigits: '', status: 'browsing' })
  expect(fixture.routeSession.leave).not.toHaveBeenCalled()
  expect(fixture.api.executeNumpadAddress).not.toHaveBeenCalled()
  expect(fixture.paints).toHaveLength(1)
  for (const digit of '112') fixture.key(digit)
  expect(fixture.api.executeNumpadAddress).toHaveBeenCalledExactlyOnceWith('112', 1)
  await fixture.settle()
  expect(fixture.routeSession.navigate).toHaveBeenCalledExactlyOnceWith('#/galaxy/system')
  fixture.runtime.stop()
})

test('cold Backspace preserves ordered input and the resolved map revision', async () => {
  const fixture = numpadRuntimeFixture()
  let resolve!: (tree: typeof numpadTree) => void
  fixture.api.getNumpadSnapshot.mockImplementationOnce(() => new Promise(done => { resolve = done }))
  fixture.runtime.start()
  for (const digit of '011') fixture.key(digit)
  fixture.runtime.keyDown({ code: 'Backspace', key: 'Backspace' }, true)
  for (const digit of '12') fixture.key(digit)
  resolve(numpadTree)
  await fixture.settle()
  expect(fixture.api.executeNumpadAddress).toHaveBeenCalledExactlyOnceWith('112', 1)
  expect(fixture.routeSession.navigate).toHaveBeenCalledExactlyOnceWith('#/galaxy/system')
  fixture.runtime.stop()
})

test('Backspace unarms confirmation while an executing command retains completion ownership', async () => {
  const fixture = numpadRuntimeFixture()
  fixture.api.getModuleSettings.mockResolvedValue({ ...fixture.settings, numpadCommands: { ...fixture.settings.numpadCommands, alwaysConfirm: true } })
  fixture.runtime.start()
  await fixture.settle()
  for (const digit of '0112') fixture.key(digit)
  expect(fixture.runtime.controller.getSnapshot().session.status).toBe('ready')
  fixture.runtime.keyDown({ code: 'Backspace', key: 'Backspace' }, true)
  fixture.runtime.controller.confirm()
  expect(fixture.api.executeNumpadAddress).not.toHaveBeenCalled()
  fixture.key('2')
  fixture.runtime.controller.confirm()
  fixture.runtime.keyDown({ code: 'Backspace', key: 'Backspace' }, true)
  expect(fixture.api.executeNumpadAddress).toHaveBeenCalledExactlyOnceWith('112', 1)
  await fixture.settle()
  expect(fixture.routeSession.navigate).toHaveBeenCalledExactlyOnceWith('#/galaxy/system')
  fixture.runtime.stop()
})

test('cold rapid activation buffers the entire address without mounting a view', async () => {
  const fixture = numpadRuntimeFixture()
  let resolve!: (tree: typeof numpadTree) => void
  fixture.api.getNumpadSnapshot.mockImplementationOnce(() => new Promise(done => { resolve = done }))
  const runtime = fixture.runtime
  runtime.start()
  for (const digit of '0112') fixture.key(digit)
  expect(fixture.router.getSnapshot()).toEqual({ kind: 'numpad' })
  expect(fixture.api.executeNumpadAddress).not.toHaveBeenCalled()
  resolve(numpadTree)
  await fixture.settle()
  expect(fixture.api.executeNumpadAddress).toHaveBeenCalledExactlyOnceWith('112', 1)
  expect(fixture.routeSession.navigate).toHaveBeenCalledExactlyOnceWith('#/galaxy/system')
  runtime.stop()
})

test('a warm burst and repeated Enter execute once, with no intermediate paint', async () => {
  const fixture = numpadRuntimeFixture()
  fixture.runtime.start()
  await fixture.settle()
  for (const digit of '0112') fixture.key(digit)
  fixture.runtime.controller.confirm()
  fixture.key('2', true)
  expect(fixture.api.executeNumpadAddress).toHaveBeenCalledTimes(1)
  expect(fixture.runtime.controller.getSnapshot().session.status).toBe('executing')
  await fixture.settle()
  fixture.key('0')
  expect(fixture.api.getNumpadSnapshot).toHaveBeenCalledTimes(1)
  expect(fixture.paints).toHaveLength(1)
  fixture.runtime.stop()
})

test('the initial SSE announcement preserves cold buffered input and replaces the pending read', async () => {
  const fixture = numpadRuntimeFixture()
  let first!: (tree: typeof numpadTree) => void
  fixture.api.getNumpadSnapshot.mockImplementationOnce(() => new Promise(resolve => { first = resolve }))
  fixture.runtime.start()
  for (const digit of '0112') fixture.key(digit)
  fixture.changed(1)
  fixture.changed(1)
  await fixture.settle()
  first({ ...numpadTree, revision: 99 })
  await fixture.settle()
  expect(fixture.api.getNumpadSnapshot).toHaveBeenCalledTimes(2)
  expect(fixture.api.executeNumpadAddress).toHaveBeenCalledExactlyOnceWith('112', 1)
  expect(fixture.runtime.getSnapshot().tree?.revision).toBe(1)
  fixture.runtime.stop()
})

test('confirmation still requires a separate Enter and ignores autorepeat', async () => {
  const fixture = numpadRuntimeFixture()
  fixture.api.getModuleSettings.mockResolvedValue({ ...fixture.settings, numpadCommands: { ...fixture.settings.numpadCommands, alwaysConfirm: true } })
  fixture.runtime.start()
  await fixture.settle()
  for (const digit of '0112') fixture.key(digit)
  expect(fixture.runtime.controller.getSnapshot().session.status).toBe('ready')
  fixture.runtime.keyDown({ code: 'NumpadEnter', key: 'Enter', repeat: true }, true)
  expect(fixture.api.executeNumpadAddress).not.toHaveBeenCalled()
  fixture.runtime.keyDown({ code: 'NumpadEnter', key: 'Enter' }, true)
  expect(fixture.api.executeNumpadAddress).toHaveBeenCalledTimes(1)
  fixture.runtime.stop()
})

test('catalogue changes invalidate immediately; unchanged revisions do not reset input', async () => {
  const fixture = numpadRuntimeFixture()
  fixture.runtime.start()
  await fixture.settle()
  fixture.key('0'); fixture.key('1')
  fixture.changed(1)
  expect(fixture.runtime.controller.getSnapshot().session.active).toBe(true)
  expect(fixture.api.getNumpadSnapshot).toHaveBeenCalledTimes(1)
  fixture.api.getNumpadSnapshot.mockResolvedValue({ ...numpadTree, revision: 2 })
  fixture.changed(2)
  expect(fixture.runtime.controller.getSnapshot().session.active).toBe(false)
  fixture.key('1'); fixture.key('2')
  await fixture.settle()
  expect(fixture.api.executeNumpadAddress).not.toHaveBeenCalled()
  for (const digit of '0112') fixture.key(digit)
  expect(fixture.api.executeNumpadAddress).toHaveBeenCalledExactlyOnceWith('112', 2)
  fixture.runtime.stop()
})

test('a restarted catalogue and updated confirmation settings replace the cached map', async () => {
  const fixture = numpadRuntimeFixture()
  fixture.runtime.start()
  await fixture.settle()
  fixture.key('0'); fixture.key('1')
  const generatedAt = '2026-10-05T12:00:00.000Z'
  fixture.api.getNumpadSnapshot.mockResolvedValue({ ...numpadTree, generatedAt })
  fixture.api.getModuleSettings.mockResolvedValue({ ...fixture.settings, numpadCommands: { ...fixture.settings.numpadCommands, alwaysConfirm: true } })
  fixture.changed(1, generatedAt)
  expect(fixture.runtime.controller.getSnapshot().session.active).toBe(false)
  await fixture.settle()
  for (const digit of '0112') fixture.key(digit)
  expect(fixture.runtime.controller.getSnapshot().session.status).toBe('ready')
  expect(fixture.api.executeNumpadAddress).not.toHaveBeenCalled()
  fixture.runtime.stop()
})

test.each(['cancel', 'route', 'stop', 'revision'] as const)('late execution cannot navigate after %s', async mode => {
  const fixture = numpadRuntimeFixture()
  let resolve!: (value: Awaited<ReturnType<typeof fixture.api.executeNumpadAddress>>) => void
  fixture.api.executeNumpadAddress.mockImplementationOnce(() => new Promise(done => { resolve = done }))
  fixture.runtime.start()
  await fixture.settle()
  for (const digit of '0112') fixture.key(digit)
  if (mode === 'cancel') fixture.runtime.controller.cancel()
  else if (mode === 'route') fixture.router.push({ kind: 'controls', category: 'ship' })
  else if (mode === 'revision') fixture.changed(2)
  else fixture.runtime.stop()
  resolve(fixture.result)
  await fixture.settle()
  expect(fixture.routeSession.navigate).not.toHaveBeenCalled()
  fixture.runtime.stop()
})

test('failed map loading discards queued input; a new activation retries', async () => {
  const fixture = numpadRuntimeFixture()
  fixture.api.getNumpadSnapshot.mockRejectedValueOnce(new Error('Offline'))
  fixture.runtime.start()
  for (const digit of '0112') fixture.key(digit)
  await fixture.settle()
  expect(fixture.runtime.getSnapshot()).toMatchObject({ status: 'error', error: 'Offline' })
  expect(fixture.runtime.controller.getSnapshot().session.active).toBe(false)
  for (const digit of '0112') fixture.key(digit)
  await fixture.settle()
  expect(fixture.api.executeNumpadAddress).toHaveBeenCalledTimes(1)
  fixture.runtime.stop()
})

test('physical capture preference does not disable the Numpy page itself', async () => {
  const fixture = numpadRuntimeFixture()
  fixture.runtime.start()
  await fixture.settle()
  expect(fixture.runtime.keyDown({ code: 'Numpad0', key: '0' }, false)).toBe(false)
  fixture.router.push({ kind: 'numpad' })
  expect(fixture.runtime.keyDown({ code: 'Numpad0', key: '0' }, false)).toBe(true)
  fixture.runtime.stop()
})

test('rejected and stale server results never navigate even if they contain a command', async () => {
  for (const status of ['rejected', 'stale'] as const) {
    const fixture = numpadRuntimeFixture()
    fixture.api.executeNumpadAddress.mockResolvedValue({ ...fixture.result, status })
    fixture.runtime.start()
    await fixture.settle()
    for (const digit of '0112') fixture.key(digit)
    await fixture.settle()
    expect(fixture.routeSession.navigate).not.toHaveBeenCalled()
    expect(fixture.runtime.controller.getSnapshot().session.active).toBe(false)
    fixture.runtime.stop()
  }
})
